server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/NBT/Git/configuration
  security:
    user:
      name: admin
      password: s3cr3t
management:
  endpoints:
    web:
      exposure:
        include: "*"

