server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/NBT/Git/configuration
  security:
    user:
      name: admin
      password: s3cr3t

  boot:
    admin:
      client:
        url: http://localhost:9092
        username: admin
        password: admin


  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: "*"

